version: "3.8"

services:
  server:
    image: app
    ports:
      - "8081:8081"
    build: .
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_USER=root

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee

